export const data = [
    {
        question: "Which device is required for the Internet connection",
        Option1: "Modem",
        Option2: "Router",
        Option3: "LAN Cable",
        Option4: "Pen Drive",
        ans: 1,
    },
    {
        question: "Which continent haqs the heighes number of countres",
        Option1: "Asia",
        Option2: "Eurpoe",
        Option3: "North America",
        Option4: "Africa",
        ans: 4,
    },
    {
        question: "Junk e-mail is also called?",
        Option1: "Spam",
        Option2: "Fake",
        Option3: "Archived",
        Option4: "Bin",
        ans: 1,
    },
    {
        question: "A computer cannot BOOT if it does not have the?",
        Option1: "Application Software",
        Option2: "Internet",
        Option3: "Operating System",
        Option4: "Mouse",
        ans: 3,
    },
    {
        question: "First page of website is termed as?",
        Option1: "Index Page",
        Option2: "HomePage",
        Option3: "Sitemap",
        Option4: "pen Drive",
        ans: 2,
    },
];